# Generated by Django 5.0.1 on 2024-01-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListTexter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_texter', models.CharField(max_length=20)),
                ('name_texter', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='list/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
